# Generated by Django 5.1.15 on 2026-10-05 17:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingapp', '0004_test_batches'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('channel', models.CharField(default='both', max_length=16)),
                ('is_promo', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('kind', models.CharField(default='message', max_length=20)),
                ('ref', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='moderation_note',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='report',
            name='related_ref',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='can_moderate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailtoken',
            name='purpose',
            field=models.CharField(choices=[('verify', 'verify'), ('reset', 'reset'), ('partner', 'partner'), ('invite', 'invite')], max_length=16),
        ),
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='moderation_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée'), ('removed', 'Retirée')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='testbatch',
            name='status',
            field=models.CharField(choices=[('queued', 'En file'), ('generating', 'Génération'), ('images_blocked', 'Images indisponibles'), ('packaged', 'Paquet prêt'), ('imported', 'Importé'), ('failed', 'Échec'), ('deleted', 'Supprimé')], default='queued', max_length=24),
        ),
        migrations.AlterField(
            model_name='user',
            name='age_proof_status',
            field=models.CharField(choices=[('unconfirmed', 'Non confirmé par la personne'), ('declared', 'Déclaration seulement'), ('pending_review', 'Preuve en attente'), ('verified', 'Majorité vérifiée'), ('rejected', 'Preuve refusée')], default='declared', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('channel', models.CharField(default='notice', max_length=16)),
                ('is_promo', models.BooleanField(default=False)),
                ('criteria', models.CharField(blank=True, max_length=300)),
                ('client_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swingapp.messagetemplate')),
            ],
        ),
        migrations.CreateModel(
            name='ReportNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('action', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='swingapp.report')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=16)),
                ('detail', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='swingapp.campaign')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swingapp.notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swingapp.outboundemail')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('campaign', 'user'), name='uniq_campaign_user')],
            },
        ),
    ]
