# Generated by Django 5.1.15 on 2026-10-06 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingapp', '0006_access_perms'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(unique=True)),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(default='off', max_length=16)),
                ('status', models.CharField(default='unconfigured', max_length=16)),
                ('public_data', models.JSONField(blank=True, default=dict)),
                ('secret_data', models.TextField(blank=True)),
                ('last_test_at', models.DateTimeField(blank=True, null=True)),
                ('last_test_ok', models.BooleanField(null=True)),
                ('last_test_message', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='byte_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='duration_s',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='estimated_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='height',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='photo',
            name='source_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='photo',
            name='thumb',
            field=models.ImageField(blank=True, upload_to='thumbs/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='photo',
            name='width',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MediaUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32, unique=True)),
                ('kind', models.CharField(default='video', max_length=8)),
                ('filename', models.CharField(blank=True, max_length=120)),
                ('total_size', models.BigIntegerField(default=0)),
                ('received', models.BigIntegerField(default=0)),
                ('next_index', models.PositiveIntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('status', models.CharField(default='uploading', max_length=16)),
                ('temp_path', models.CharField(blank=True, max_length=500)),
                ('error', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swingapp.photo')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='swingapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint_hash', models.CharField(max_length=64, unique=True)),
                ('endpoint', models.TextField()),
                ('p256dh', models.CharField(max_length=200)),
                ('auth', models.CharField(max_length=120)),
                ('user_agent', models.CharField(blank=True, max_length=200)),
                ('kinds', models.JSONField(blank=True, default=dict)),
                ('disabled', models.BooleanField(default=False)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
