# Generated by Django 5.1.15 on 2026-10-09 02:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingapp', '0012_profile_travel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kind',
            field=models.CharField(choices=[('single', 'Célibataire'), ('couple', 'Couple'), ('business', 'Entreprise')], default='single', max_length=16),
        ),
        migrations.CreateModel(
            name='BusinessAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('club', 'club'), ('sauna', 'sauna'), ('party', 'party'), ('travel', 'travel'), ('cruise', 'cruise'), ('shop', 'shop'), ('photo', 'photo'), ('organizer', 'organizer'), ('other', 'other')], default='other', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(blank=True, max_length=160)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('ticket_url', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='business/logos/')),
                ('verified', models.BooleanField(default=False)),
                ('plan_status', models.CharField(choices=[('none', 'none'), ('active', 'active'), ('unpaid', 'unpaid'), ('canceled', 'canceled')], default='none', max_length=16)),
                ('plan_until', models.DateField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to='swingapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='business/docs/')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], default='pending', max_length=16)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='swingapp.businessaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('plan', 'plan'), ('push', 'push')], max_length=16)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('due', 'due'), ('paid', 'paid'), ('void', 'void')], default='due', max_length=16)),
                ('note', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='swingapp.businessaccount')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business/photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='swingapp.businessaccount')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(default='party', max_length=16)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('place', models.CharField(blank=True, max_length=160)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('practical', models.TextField(blank=True)),
                ('price_note', models.CharField(blank=True, max_length=240)),
                ('ticket_url', models.CharField(blank=True, max_length=200)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='swingapp.businessaccount')),
            ],
            options={
                'ordering': ['starts_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=80)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('radius_km', models.PositiveIntegerField(default=30)),
                ('category', models.CharField(blank=True, max_length=32)),
                ('body', models.TextField()),
                ('audience', models.PositiveIntegerField(default=0)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes', to='swingapp.businessaccount')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swingapp.campaign')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='swingapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='business/events/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='swingapp.event')),
            ],
        ),
        migrations.CreateModel(
            name='EventRsvp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('interested', 'interested'), ('going', 'going'), ('waitlist', 'waitlist')], default='interested', max_length=16)),
                ('anonymous', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rsvps', to='swingapp.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_rsvps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('event', 'user'), name='uniq_event_rsvp')],
            },
        ),
    ]
