# Generated by Django 5.1.15 on 2026-10-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingapp', '0013_businesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seeking_serious',
            field=models.BooleanField(default=False),
        ),
    ]
