# Generated by Django 5.1.15 on 2026-10-10 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingapp', '0014_seeking_serious'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessaccount',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_businesses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessinvoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessinvoice',
            name='payment_ref',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='businessinvoice',
            name='payment_url',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='businessinvoice',
            name='sold_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesspush',
            name='offer_details',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
        migrations.AddField(
            model_name='businesspush',
            name='offer_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesspush',
            name='promo_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='businesspush',
            name='purpose',
            field=models.CharField(default='ad', max_length=16),
        ),
        migrations.AddField(
            model_name='businesspush',
            name='target_kinds',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('contact', models.CharField(blank=True, default='', max_length=80)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('category', models.CharField(blank=True, default='other', max_length=16)),
                ('status', models.CharField(choices=[('new', 'new'), ('contacted', 'contacted'), ('follow', 'follow'), ('client', 'client'), ('lost', 'lost')], default='new', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('next_follow', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to='swingapp.businessaccount')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_follow', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SellerPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('seller', 'period'), name='uniq_seller_period')],
            },
        ),
    ]
