# Generated by Django 5.1.15 on 2026-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingapp', '0015_business_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='html_body',
            field=models.TextField(blank=True, default=''),
        ),
    ]
