# Generated by Django 5.1.15 on 2026-10-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swingapp', '0016_email_html_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='holder_name',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
